Gallery/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Gallery.Models
{
    public class Photo
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        public string AltText { get; set; }

        [DataType(DataType.Html)]
        public string Caption { get; set; }

        [Required]
        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        private DateTime? createdDate;       
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime CreatedDate
        {
            get { return createdDate ?? DateTime.Now; }
            set { createdDate = value; }
        }
    }
}

Gallery/Models/PhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gallery.Models
{
    public class PhotoViewModel
    {
        [Required]
        public string Title { get; set; }

        public string AltText { get; set; }

        [DataType(DataType.Html)]
        public string Caption { get; set; }

        [DataType(DataType.Upload)]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}

Gallery/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gallery.Models;

namespace Gallery.Controllers
{
    public class PhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Photos
        public ActionResult Index()
        {
            return View(db.Photos.ToList());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            return View(db.Photos.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        [Authorize]
        public ActionResult Create()
        {
            return View(new PhotoViewModel());
        }

        // POST: Photos/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PhotoViewModel model)
        {
            var image = new Photo();
            var validImageTypes = new string[]
            {
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png"
            };

            if (model.ImageUpload == null || model.ImageUpload.ContentLength == 0)
            {
                ModelState.AddModelError("ImageUpload", "This field is required");
            }
            else if (!validImageTypes.Contains(model.ImageUpload.ContentType))
            {
                ModelState.AddModelError("ImageUpload", "Please choose either a GIF, JPG or PNG image.");
            }

            if (ModelState.IsValid)
            {
                image = new Photo
                {
                    Title = model.Title,
                    AltText = model.AltText,
                    Caption = model.Caption
                };

                if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
                {
                    var uploadDir = "~/uploads";
                    var getDir = "/uploads";
                    var imagePath = Path.Combine(Server.MapPath(uploadDir), model.ImageUpload.FileName);
                    var imageUrl = Path.Combine(getDir, model.ImageUpload.FileName);
                    model.ImageUpload.SaveAs(imagePath);
                    image.ImageUrl = imageUrl;
                };

                db.Photos.Add(image);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        // GET: Photos/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var image = db.Photos.Find(id);
            if (image == null)
            {
                return new HttpNotFoundResult();
            }

            var model = new PhotoViewModel
            {
                Title = image.Title,
                AltText = image.AltText,
                Caption = image.Caption
            };

        return View(model);
        }

        // POST: Photos/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PhotoViewModel model)
        {
            var validImageTypes = new string[]
            {
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png"
            };

            if (model.ImageUpload != null || model.ImageUpload.ContentLength > 0 && !validImageTypes.Contains(model.ImageUpload.ContentType))
            {
                ModelState.AddModelError("ImageUpload", "Please choose either a GIF, JPG or PNG image.");
            }

            if (ModelState.IsValid)
            {
                var image = db.Photos.Find(id);
                if (image == null)
                {
                    return new HttpNotFoundResult();
                }

                image.Title = model.Title;
                image.AltText = model.AltText;
                image.Caption = model.Caption;

                if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
                {
                    var uploadDir = "~/uploads";
                    var getDir = "/uploads";
                    var imagePath = Path.Combine(Server.MapPath(uploadDir), model.ImageUpload.FileName);
                    var imageUrl = Path.Combine(getDir, model.ImageUpload.FileName);
                    model.ImageUpload.SaveAs(imagePath);
                    image.ImageUrl = imageUrl;
                }

                db.Entry(image).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(model);
        }

        // GET: Photos/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gallery/Views/Photos/Create.cshtml
@model Gallery.Models.PhotoViewModel

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h2>Dodaj obraz</h2>

    <div>
        @Html.LabelFor(m => m.Title)
        @Html.EditorFor(m => m.Title)
    </div>
    <div>
        @Html.LabelFor(m => m.AltText)
        @Html.EditorFor(m => m.AltText)
    </div>
    <div>
        @Html.LabelFor(m => m.Caption)
        @Html.EditorFor(m => m.Caption)
    </div>
    <div>
        @Html.LabelFor(m => m.ImageUpload)
        @Html.TextBoxFor(m => m.ImageUpload, new { type = "file" })
    </div>
    <button type="submit" class="btn-primary">Dodaj</button>
</form>

Gallery/Views/Photos/Delete.cshtml
@model Gallery.Models.Photo


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do przeglądu obrazów", "List")
        </div>
    }
</div>

Gallery/Views/Photos/Details.cshtml
@model Gallery.Models.Photo


    <h2>@Html.DisplayFor(model => model.Title)</h2>

<div>
    <div class="row">
        <a href="@Html.DisplayFor(model => model.ImageUrl)">
            <img class="thumbnail col-md-10" src="@Html.DisplayFor(model => model.ImageUrl)" title="@Html.DisplayFor(model => model.Title)" alt="@Html.DisplayFor(model => model.AltText)" />
        </a>
    </div>
    <div class="row">
        <a class="btn-download" href="@Html.DisplayFor(model => model.ImageUrl)" download>
            Pobierz
        </a>
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@

    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Do strony głównej", "Index", "Home") <span>|</span>
        @Html.ActionLink("Wróć do przeglądu obrazów", "List", "Photos")
    }
    else
    {
        @Html.ActionLink("Wróć", "Index", "Home")
    }
</p>

Gallery/Views/Photos/Edit.cshtml
@model Gallery.Models.PhotoViewModel


<h2>Edit</h2>

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true);

    <div>
        @Html.LabelFor(m => m.Title)
        @Html.EditorFor(m => m.Title)
    </div>
    <div>
        @Html.LabelFor(m => m.AltText)
        @Html.EditorFor(m => m.AltText)
    </div>
    <div>
        @Html.LabelFor(m => m.Caption)
        @Html.EditorFor(m => m.Caption)
    </div>
    <div>
        @Html.LabelFor(m => m.ImageUpload)
        @Html.TextBoxFor(m => m.ImageUpload, new { type = "file" })
    </div>
    <button type="submit">Edytuj</button>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gallery/Views/Photos/Index.cshtml
@model IEnumerable<Gallery.Models.Photo>

@*@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Photos/Index.cshtml";
}*@

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AltText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Caption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AltText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Caption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Gallery/Views/Photos/List.cshtml
@model IEnumerable<Gallery.Models.Photo>

    <h2>Przegląd obrazów</h2>
    @*<p>
        @Html.ActionLink("Dodaj obraz", "Create")
    </p>*@

        @foreach (var item in Model)
        {
        <div class="row">
            <img class="thumbnail col-md-3" src="@Html.DisplayFor(modelItem => item.ImageUrl)" title="@Html.DisplayFor(modelItem => item.Title)" alt="@Html.DisplayFor(modelItem => item.AltText)" />
            <div class="col-md-6">
                @Html.DisplayFor(modelItem => item.Title)
                <br />
                @Html.DisplayFor(modelItem => item.ImageUrl)
                <br />
                @Html.DisplayFor(modelItem => item.Caption)
                <br />
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </div>
            <div class="col-md-6">
                @if (User.IsInRole("Admin"))
                {
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) <span>|</span>*@
                @Html.ActionLink("Podgląd", "Details", new { id = item.Id }) <span>|</span>
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
                }
            </div>


        </div>
}